"""model-message — AI SDK ergonomics (ModelMessage, generate_text, stream_text)
for Python, with OpenAI, Anthropic, Google Gemini, and OpenRouter providers.

    from model_message import generate_text
    from model_message.providers import anthropic

    result = await generate_text(
        model=anthropic("claude-opus-4-8"),
        prompt="What is the capital of France?",
    )
    print(result.text)
"""

from .agent import Agent
from .errors import (
    AbortError,
    AISDKError,
    APICallError,
    GenerationTimeoutError,
    InvalidPromptError,
    InvalidToolInputError,
    MissingDependencyError,
    NoObjectGeneratedError,
    NoSuchProviderError,
    NoSuchToolError,
)
from .generate import (
    PrepareStepFn,
    PrepareStepResult,
    RepairToolCallFn,
    StreamTextResult,
    generate_id,
    generate_text,
    has_tool_call,
    step_count_is,
    stream_text,
)
from .messages import (
    AssistantContent,
    AssistantModelMessage,
    ContentOutput,
    DataContent,
    DataOrFileId,
    DocumentSourcePart,
    ErrorJsonOutput,
    ErrorTextOutput,
    FileDataContentItem,
    FileIdData,
    FilePart,
    FileUrlContentItem,
    ImageDataContentItem,
    ImagePart,
    ImageUrlContentItem,
    JsonOutput,
    MediaContentItem,
    ModelMessage,
    ProviderOptions,
    ReasoningPart,
    SourcePart,
    SystemModelMessage,
    TextContentItem,
    TextOutput,
    TextPart,
    ToolApprovalRequest,
    ToolApprovalResponse,
    ToolCallPart,
    ToolContent,
    ToolModelMessage,
    ToolResultOutput,
    ToolResultPart,
    UrlSourcePart,
    UserContent,
    UserModelMessage,
    model_message_adapter,
    model_messages_adapter,
)
from .output import (
    GenerateObjectResult,
    Output,
    StreamObjectResult,
    generate_object,
    parse_partial_json,
    stream_object,
)
from .provider import CallOptions, FunctionToolSpec, LanguageModel, ProviderResult
from .results import (
    CallWarning,
    FinishReason,
    GeneratedFile,
    GenerateTextResult,
    InputTokenDetails,
    OutputTokenDetails,
    ResponseMetadata,
    StepResult,
    ToolChoice,
    ToolResult,
    Usage,
)
from .stream import (
    AbortPart,
    ErrorPart,
    Finish,
    FinishStep,
    FilePartEvent,
    RawPart,
    ReasoningDelta,
    ReasoningEnd,
    ReasoningStart,
    ResponseMetadataPart,
    SourceStreamPart,
    StartStep,
    StreamStart,
    TextDelta,
    TextEnd,
    TextStart,
    TextStreamPart,
    ToolErrorEvent,
    ToolInputDelta,
    ToolInputEnd,
    ToolInputStart,
    ToolResultEvent,
)
from .tools import Tool, ToolCallOptions, ToolSet, tool
from .transforms import Transform, compose_transforms, smooth_stream

__version__ = "0.2.0"

__all__ = [
    # core functions
    "generate_text",
    "stream_text",
    "StreamTextResult",
    "generate_object",
    "stream_object",
    "GenerateObjectResult",
    "StreamObjectResult",
    "Output",
    "parse_partial_json",
    "Agent",
    "PrepareStepResult",
    "PrepareStepFn",
    "RepairToolCallFn",
    "Transform",
    "smooth_stream",
    "compose_transforms",
    "tool",
    "Tool",
    "ToolSet",
    "ToolCallOptions",
    "step_count_is",
    "has_tool_call",
    "generate_id",
    # messages & parts
    "ModelMessage",
    "SystemModelMessage",
    "UserModelMessage",
    "AssistantModelMessage",
    "ToolModelMessage",
    "UserContent",
    "AssistantContent",
    "ToolContent",
    "TextPart",
    "ImagePart",
    "FilePart",
    "ReasoningPart",
    "ToolCallPart",
    "ToolResultPart",
    "ToolResultOutput",
    "TextOutput",
    "JsonOutput",
    "ErrorTextOutput",
    "ErrorJsonOutput",
    "ContentOutput",
    "TextContentItem",
    "MediaContentItem",
    "FileDataContentItem",
    "FileUrlContentItem",
    "ImageDataContentItem",
    "ImageUrlContentItem",
    "DataContent",
    "DataOrFileId",
    "FileIdData",
    "SourcePart",
    "UrlSourcePart",
    "DocumentSourcePart",
    "ToolApprovalRequest",
    "ToolApprovalResponse",
    "ProviderOptions",
    "model_message_adapter",
    "model_messages_adapter",
    # results
    "GenerateTextResult",
    "StepResult",
    "ToolResult",
    "Usage",
    "InputTokenDetails",
    "OutputTokenDetails",
    "CallWarning",
    "GeneratedFile",
    "FinishReason",
    "ResponseMetadata",
    "ToolChoice",
    # stream parts
    "TextStreamPart",
    "StreamStart",
    "StartStep",
    "TextStart",
    "TextDelta",
    "TextEnd",
    "ReasoningStart",
    "ReasoningDelta",
    "ReasoningEnd",
    "ToolInputStart",
    "ToolInputDelta",
    "ToolInputEnd",
    "ToolResultEvent",
    "ToolErrorEvent",
    "FilePartEvent",
    "SourceStreamPart",
    "ResponseMetadataPart",
    "FinishStep",
    "Finish",
    "ErrorPart",
    "RawPart",
    "AbortPart",
    # provider interface
    "LanguageModel",
    "CallOptions",
    "ProviderResult",
    "FunctionToolSpec",
    # errors
    "AISDKError",
    "APICallError",
    "NoSuchToolError",
    "NoObjectGeneratedError",
    "InvalidToolInputError",
    "InvalidPromptError",
    "NoSuchProviderError",
    "MissingDependencyError",
    "AbortError",
    "GenerationTimeoutError",
]
