"""model-message — AI SDK ergonomics (ModelMessage, generate_text, stream_text)
for Python, with OpenAI, Anthropic, Google Gemini, and OpenRouter providers.

    from pai_sdk import generate_text
    from pai_sdk.providers import anthropic

    result = await generate_text(
        model=anthropic("claude-opus-4-8"),
        prompt="What is the capital of France?",
    )
    print(result.text)
"""

from .agent import Agent
from .embedding import (
    EmbeddingModel,
    EmbeddingUsage,
    EmbedManyResult,
    EmbedResult,
    cosine_similarity,
    embed,
    embed_many,
)
from .errors import (
    AbortError,
    AISDKError,
    APICallError,
    GenerationTimeoutError,
    InvalidPromptError,
    InvalidToolInputError,
    MissingDependencyError,
    NoObjectGeneratedError,
    NoSuchProviderError,
    NoSuchToolError,
)
from .generate import (
    PrepareStepFn,
    PrepareStepResult,
    RepairToolCallFn,
    StreamTextResult,
    generate_id,
    generate_text,
    has_tool_call,
    step_count_is,
    stream_text,
)
from .messages import (
    AssistantContent,
    AssistantModelMessage,
    ContentOutput,
    DataContent,
    DataOrFileId,
    DocumentSourcePart,
    ErrorJsonOutput,
    ErrorTextOutput,
    FileDataContentItem,
    FileIdData,
    FilePart,
    FileUrlContentItem,
    ImageDataContentItem,
    ImagePart,
    ImageUrlContentItem,
    JsonOutput,
    MediaContentItem,
    ModelMessage,
    ProviderOptions,
    ReasoningPart,
    SourcePart,
    SystemModelMessage,
    TextContentItem,
    TextOutput,
    TextPart,
    ToolApprovalRequest,
    ToolApprovalResponse,
    ToolCallPart,
    ToolContent,
    ToolModelMessage,
    ToolResultOutput,
    ToolResultPart,
    UrlSourcePart,
    UserContent,
    UserModelMessage,
    pai_sdk_adapter,
    pai_sdks_adapter,
)
from .middleware import (
    LanguageModelMiddleware,
    default_settings_middleware,
    extract_reasoning_middleware,
    logging_middleware,
    simulate_streaming_middleware,
    wrap_language_model,
)
from .pricing import (
    CostEstimate,
    ModelPricing,
    NoPricingError,
    PRICING_SOURCES,
    estimate_cost,
    get_pricing,
    parse_pricing_data,
    refresh_pricing,
    register_pricing,
)
from .output import (
    GenerateObjectResult,
    Output,
    StreamObjectResult,
    generate,
    generate_object,
    parse_partial_json,
    stream,
    stream_object,
)
from .provider import CallOptions, FunctionToolSpec, LanguageModel, ProviderResult
from .serialize import dump_messages, dump_messages_json, load_messages
from .registry import (
    CustomProvider,
    ProviderRegistry,
    create_provider_registry,
    custom_provider,
)
from .results import (
    CallWarning,
    FinishReason,
    GeneratedFile,
    GenerateTextResult,
    InputTokenDetails,
    OutputTokenDetails,
    ResponseMetadata,
    StepResult,
    ToolChoice,
    ToolResult,
    Usage,
)
from .stream import (
    AbortPart,
    ErrorPart,
    Finish,
    FinishStep,
    FilePartEvent,
    RawPart,
    ReasoningDelta,
    ReasoningEnd,
    ReasoningStart,
    ResponseMetadataPart,
    SourceStreamPart,
    StartStep,
    StreamStart,
    TextDelta,
    TextEnd,
    TextStart,
    TextStreamPart,
    ToolErrorEvent,
    ToolInputDelta,
    ToolInputEnd,
    ToolInputStart,
    ToolResultEvent,
)
from .prompts import (
    PROMPT_CONFIG_SCHEMA,
    Prompt,
    PromptError,
    PromptMessage,
    compile_output_shorthand,
    load_prompt,
    load_prompt_url,
)
from .tools import Tool, ToolCallOptions, ToolSet, tool
from .transforms import Transform, compose_transforms, smooth_stream
from .typed import (
    TemplateError,
    TypedAssistantMessage,
    TypedSystemMessage,
    TypedUserMessage,
    extract_variables,
    render_template,
)

__version__ = "0.3.0"

__all__ = [
    # core functions
    "generate_text",
    "stream_text",
    "StreamTextResult",
    "generate",
    "stream",
    "generate_object",
    "stream_object",
    "GenerateObjectResult",
    "StreamObjectResult",
    "Output",
    "parse_partial_json",
    "Agent",
    "PrepareStepResult",
    "PrepareStepFn",
    "RepairToolCallFn",
    "Transform",
    "smooth_stream",
    "compose_transforms",
    # middleware
    "LanguageModelMiddleware",
    "wrap_language_model",
    "default_settings_middleware",
    "extract_reasoning_middleware",
    "simulate_streaming_middleware",
    "logging_middleware",
    # registry
    "create_provider_registry",
    "custom_provider",
    "ProviderRegistry",
    "CustomProvider",
    # embeddings
    "embed",
    "embed_many",
    "cosine_similarity",
    "EmbeddingModel",
    "EmbedResult",
    "EmbedManyResult",
    "EmbeddingUsage",
    "tool",
    "Tool",
    "ToolSet",
    "ToolCallOptions",
    "step_count_is",
    "has_tool_call",
    "generate_id",
    # messages & parts
    "ModelMessage",
    "SystemModelMessage",
    "UserModelMessage",
    "AssistantModelMessage",
    "ToolModelMessage",
    "UserContent",
    "AssistantContent",
    "ToolContent",
    "TextPart",
    "ImagePart",
    "FilePart",
    "ReasoningPart",
    "ToolCallPart",
    "ToolResultPart",
    "ToolResultOutput",
    "TextOutput",
    "JsonOutput",
    "ErrorTextOutput",
    "ErrorJsonOutput",
    "ContentOutput",
    "TextContentItem",
    "MediaContentItem",
    "FileDataContentItem",
    "FileUrlContentItem",
    "ImageDataContentItem",
    "ImageUrlContentItem",
    "DataContent",
    "DataOrFileId",
    "FileIdData",
    "SourcePart",
    "UrlSourcePart",
    "DocumentSourcePart",
    "ToolApprovalRequest",
    "ToolApprovalResponse",
    "ProviderOptions",
    "pai_sdk_adapter",
    "pai_sdks_adapter",
    "dump_messages",
    "dump_messages_json",
    "load_messages",
    # results
    "GenerateTextResult",
    "StepResult",
    "ToolResult",
    "Usage",
    "InputTokenDetails",
    "OutputTokenDetails",
    "CallWarning",
    "GeneratedFile",
    "FinishReason",
    "ResponseMetadata",
    "ToolChoice",
    # stream parts
    "TextStreamPart",
    "StreamStart",
    "StartStep",
    "TextStart",
    "TextDelta",
    "TextEnd",
    "ReasoningStart",
    "ReasoningDelta",
    "ReasoningEnd",
    "ToolInputStart",
    "ToolInputDelta",
    "ToolInputEnd",
    "ToolResultEvent",
    "ToolErrorEvent",
    "FilePartEvent",
    "SourceStreamPart",
    "ResponseMetadataPart",
    "FinishStep",
    "Finish",
    "ErrorPart",
    "RawPart",
    "AbortPart",
    # provider interface
    "LanguageModel",
    "CallOptions",
    "ProviderResult",
    "FunctionToolSpec",
    # errors
    "AISDKError",
    "APICallError",
    "NoSuchToolError",
    "NoObjectGeneratedError",
    "InvalidToolInputError",
    "InvalidPromptError",
    "NoSuchProviderError",
    "MissingDependencyError",
    "AbortError",
    "GenerationTimeoutError",
    # pricing
    "estimate_cost",
    "get_pricing",
    "register_pricing",
    "ModelPricing",
    "CostEstimate",
    "NoPricingError",
    "refresh_pricing",
    "parse_pricing_data",
    "PRICING_SOURCES",
    # typed messages & prompt configs
    "TypedSystemMessage",
    "TypedUserMessage",
    "TypedAssistantMessage",
    "TemplateError",
    "extract_variables",
    "render_template",
    "Prompt",
    "PromptMessage",
    "PromptError",
    "load_prompt",
    "load_prompt_url",
    "compile_output_shorthand",
    "PROMPT_CONFIG_SCHEMA",
]
